spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.main.banner-mode=off
logging.level.org.hibernate=WARN
logging.level.org.springframework=WARN
logging.level.org.apache.catalina=WARN
logging.level.com.zaxxer.hikari=WARN
spring.jpa.open-in-view=false

spring.security.oauth2.client.registration.google.client-id=1059917644222-0jbo7rcfotmn66uij8jr0ti489uss6if.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
server.forward-headers-strategy=FRAMEWORK

server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true