spring.datasource.username=root
spring.datasource.password=1990
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/pushups
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.main.banner-mode=off
logging.level.org.hibernate=WARN
logging.level.org.springframework=WARN
logging.level.org.apache.catalina=WARN
logging.level.com.zaxxer.hikari=WARN
spring.jpa.open-in-view=true

springdoc.swagger-ui.path=/docs